name: Python CI with uv

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then
          ~/.cargo/bin/uv pip install -r requirements.txt
        elif [ -f pyproject.toml ]; then
          ~/.cargo/bin/uv pip install .
        fi
        ~/.cargo/bin/uv pip install pytest

    - name: Run tests
      run: ~/.cargo/bin/uv pip run pytest